### ISSUE TITLE
Change definition hint panel to use definition hints rather than full word definitions

### ISSUE THREAD

**Issue by apmwebdev** [apmwebdev/spelling-bee#113]
Full word definitions are not ideal for the definition hint panel. The idea of the definition hint panel is to give a hint about what the word is by giving its meaning without showing the actual word itself, but the problem is that the definitions often include the root of the word or a similar derivative of the word being defined. For example, the definition for `bubbly` is "Full of bubbles." This gives away too much information.

I don't know of an API that is just for "word definition hints," so the best approach here is likely to use an AI service to generate definition hints for each word. I've done a little bit of testing in ChatGPT, and this seems to be doable with explicit instructions about what you want the hints to include and exclude and what format you want the response to be in.

This prompt worked well for ChatGPT 3.5, so I assume it would work with the OpenAI API as well:

```
Provide definition hints for the following words:

    aioli
    alit
    allay
    allot
    alloy
    ally
    alto
    atilt
    atoll
    avail
    iota
    laity
    lava
    loyal
    loyally
    loyalty
    oaty
    oval
    tail
    tali
    tall
    tallit
    tally
    tattoo
    tatty
    total
    totality
    totally
    vial
    villa
    viola
    vital
    vitality
    vitally
    voila
    volatility

Respond in JSON format. There should be an outer object containing an array with the key "wordHints".
The array should contain an object for each word. The keys in this object should be "word",
which contains the word itself, and "hint", which contains your hint. An example of this format would be:

{
  wordHints: [
    {
      word: "aioli",
      hint: "Hint text for 'aioli'",
    },
    {
      word: "alit",
      hint: "Hint text for 'alit'",
    },
  ]
}

Each hint should be one or two sentences and should not contain any form of the word you're
providing a hint for. For example, the hint for "allay" should not contain "allay," "allaying," "allays,"
and so forth. The hints should focus on the meaning of the word, although hints about the pronunciation
of the word are also acceptable.

These hints are designed to replicate the user-provided hints that users provide on the New York Times
Spelling Bee forums for words in that day's Spelling Bee puzzle.

Please respond only with the JSON object and nothing else.
```

Getting word hint definitions for puzzle answers that don't already have hint definitions could become part of the process of adding new puzzles. The GPT API is very cheap, especially for GPT 3.5, so this would likely be a minimal expense. Still, the Sync API should be used to get the hint definitions to dev environments so that the expense of generating hints wouldn't have to be incurred more than once.

## Tasks
- [x] Update word model with hint column
- [x] Add models for hint requests and responses
- [x] Integrate API key into dev, test, and prod env
- [x] Add API service
- [x] Add hint creation logic to API service
- [x] Add batching logic to API service
- [x] Add Rake tasks for generating hints for existing puzzles
- [x] Add tests for existing puzzle hint generation
- [x] Add sync logic for existing puzzle hints
- [x] Integrate hint generation with puzzle scraper
- [x] Add tests for puzzle scraper hint generation
- [x] Add hints to sync API puzzle data
- [x] Send hints to front end
- [x] Update TS types
- [x] Display hints instead of definitions in definition panel
